// Generated by CoffeeScript 1.10.0

/*
 * 测试 Promise
 * @author jackie Lin <dashi_lin@163.com>
 */
var promise;

promise = null;

describe('Promise', function() {
  it('#new Promise', function() {
    return promise = new Promise(function(resolve, reject) {
      return window.setTimeout(function() {
        return resolve(111);
      }, 1000);
    });
  });
  it('then test normal', function() {
    return promise.then(function(res) {
      return 333;
    }).then(function(res) {
      return res.should.be.exactly(333);
    });
  });
  it('then test promise', function(done) {
    return promise.then(function(res) {
      return 333;
    }).then(function(res) {
      res.should.be.exactly(333);
      return 333;
    }).then(function(res) {
      return new Promise(function(resolve, reject) {
        return window.setTimeout(function() {
          return resolve(222);
        }, 500);
      }).then(function(res) {
        res.should.be.exactly(222);
        return 444;
      }).done(function(res) {
        return res;
      });
    }).then(function(res) {
      res.should.be.exactly(444);
      return res;
    }).done(function(res) {
      return done();
    });
  });
  return it('promise fail', function(done) {
    return new Promise(function(resolve, reject) {
      return reject('error');
    }).fail(function(res) {
      res.should.be.exactly('error');
      return done();
    });
  });
});
