// Generated by CoffeeScript 1.10.0

/*
 * 测试 Promise
 * @author jackie Lin <dashi_lin@163.com>
 */
var promise;

promise = null;

describe('Promise', function() {
  it('#new Promise', function() {
    return promise = new Promise(function(resolve, reject) {
      return window.setTimeout(function() {
        return resolve(111);
      }, 1000);
    });
  });
  it('thenPromise test normal', function(donePromise) {
    return promise.thenPromise(function(res) {
      return 333;
    }).thenPromise(function(res) {
      res.should.be.exactly(333);
      return donePromise();
    });
  });
  return it('thenPromise test promise', function(donePromise) {
    return promise.thenPromise(function(res) {
      return 333;
    }).thenPromise(function(res) {
      res.should.be.exactly(333);
      return 333;
    }).thenPromise(function(res) {
      return new Promise(function(resolve, reject) {
        return window.setTimeout(function() {
          return resolve(222);
        }, 500);
      }).thenPromise(function(res) {
        res.should.be.exactly(222);
        return 444;
      }).donePromise(function(res) {
        return res;
      });
    }).thenPromise(function(res) {
      res.should.be.exactly(444);
      return res;
    }).donePromise(function(res) {
      return donePromise();
    });
  });
});
