// Generated by CoffeeScript 1.10.0

/*
 * promise 信息
 * @author jackie Lin <dashi_lin@163.com>
 * @date 2016-3-9
 */
'use strict';
(function(window) {

  /*
   * promise list
   */
  var Promise, bind, getPrevPromise, promises;
  promises = [];
  Promise = function(cb) {
    if (cb == null) {
      cb = function() {};
    }
    this.init();
    this._cb = cb;

    /*
     * 0 - pending
     * 1 - fulfilled with _value
     * 2 - rejected with _value
     * 3 - adopted the state of another promise, _value
     */
    this._status = 0;
    this._value = null;
    this._deferred = [];
    this._async = false;
    promises.push(this);
    return this._cb.apply(null, [this.resolve.bind(this), this.reject.bind(this)]);
  };

  /*
   * 绑定方法到对应的上下文
   */
  bind = function(context) {
    var aArgs, fToBind, warpperFunc;
    if (context == null) {
      context = this;
    }
    if (this !== 'function') {
      throw new TypeError('绑定对象应该是一个方法');
    }
    aArgs = Array.prototype.slice.call(arguments, 1);
    fToBind = this;
    warpperFunc = function() {
      return fToBind.apply(context, aArgs.concat(Array.prototype.slice.call(arguments)));
    };
    return warpperFunc;
  };

  /*
   * 初始化操作
   */
  Promise.prototype.init = function() {
    this._status = 0;
    this._value = null;
    if (!Function.prototype.bind) {
      return Function.prototype.bind = bind;
    }
  };

  /*
   * 执行  then 队列
   */
  Promise.prototype.resolve = function(res) {
    this._status = 1;
    this._value = res;
    this.run();
    this.next();
    return this;
  };
  Promise.prototype.reject = function(res) {
    this._status = 2;
    this._value = res;
    return this;
  };

  /*
   * 抛异常处理
   */
  Promise.prototype.fail = function(cb) {
    if (this._status !== 2) {
      return false;
    }
    this._value = cb.apply(this, [this._value]);
    return this;
  };

  /*
   * 下一步控制
   */
  Promise.prototype.next = function() {
    if (!this._done && promises.length && !this._deferred.length) {
      return this.notify();
    }
  };

  /*
   * 执行 then 方法
   */
  Promise.prototype.run = function() {
    this.doThen();
    if (this._done) {
      return this.doDone(this._done);
    }
  };

  /*
   * then 方法
   */
  Promise.prototype.then = function(cb) {
    var ref;
    if ((ref = this._status) === 0 || ref === 3) {
      this._async = true;
      this._deferred.push(cb);
    }
    if (this._status === 1) {
      this._async = false;
      this.handleThen(cb);
    }
    return this;
  };

  /*
   * 执行 then
   */
  Promise.prototype.doThen = function() {
    if (!this._deferred.length) {
      return;
    }
    if (this._deferred.length && this._status === 1) {
      return this.handleThen(this._deferred.shift(), (function(_this) {
        return function() {
          return _this.doThen();
        };
      })(this));
    }
  };

  /*
   * 执行回调方法
   */
  Promise.prototype.handleThen = function(func, callback) {
    var _value;
    if (callback == null) {
      callback = function() {};
    }
    _value = func.apply(this, [this._value]);
    if (_value instanceof Promise && _value._async) {
      return this._status = 3;
    } else if (_value instanceof Promise && !_value._async) {
      this._value = _value._value;
      promises.pop();
      return callback.apply(this);
    } else {
      this._value = _value;
      return callback.apply(this);
    }
  };

  /*
   * 将对应的值同步到上一个空间
   */
  Promise.prototype.notify = function() {
    var prev;
    prev = getPrevPromise();
    if (prev) {
      prev._value = this._value;
      promises.pop();
      prev._status = 1;
      return prev.run();
    }
  };

  /*
   * 获取上一个 promise 列表
   */
  getPrevPromise = function() {
    var length, prev;
    length = promises.length;
    prev = null;
    if (length > 1) {
      prev = promises[length - 2];
    }
    return prev;
  };
  Promise.prototype.doDone = function(done) {
    var prev;
    this._value = done.apply(this, [this._value]);
    this.notify();
    promises.pop();
    if (promises.length) {
      prev = promises[promises.length - 1];
      prev._status = 1;
      return prev.run();
    }
  };

  /*
   * 结束
   */
  Promise.prototype.done = function(cb) {
    var ref;
    if ((ref = this._status) === 0 || ref === 3) {
      this._done = cb;
    }
    if (this._status === 1) {
      this.doThen();
      this.doDone(cb);
    }
    return this;
  };
  if (!window.define) {
    return window.Promise = Promise;
  }
  if (window.define) {
    return window.define(function() {
      return Promise;
    });
  }
})(window);
